#!/usr/bin/env python3

import random

def generate():
    return random.choice([1, 0])

for _ in range(4):
    print(generate())

# Generate and print a random integer from 1 to 4
print(random.randint(1, 4))